// src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {
  gene_list_url: string = ' '
  constructor() {
    if(environment.gene_list_url) {
      this.gene_list_url = environment.gene_list_url;
    }
  }

}

<footer class="footer">
  <div class="footer-links-container">
		<img src="../../assets/external/logos/footer-logo.png" alt="Logo" class="footer-logo">
      <div class="footer-links">
        <a href="/home">HOME</a>
        <a href="/about">ABOUT</a>
        <!-- <a href="/study-tracker">DATA</a> -->
        <a href="{{gene_list_url}}">GENE LIST</a>
        <a href="/home#faq">FAQ</a>
        <!-- <a >CONTACT US</a> -->
      </div>
  </div>
  <div class="sentances">
	  <p class="footer-text">Molecular Phenotypes of Null Alleles in Cells</p>
	  <div class="right-content">
	    <p class="footer-credit">Photo by Sangharsh Lohakare on Unsplash.</p>
	    <p class="footer-copy">&copy; 2023 MorPhic. All rights reserved.</p>
	  </div>
	</div>
</footer>

// react-app/src/components/Footer.js
import { Link } from "gatsby"
import React from "react"

import { StaticImage } from "gatsby-plugin-image"

export default function Footer() {
  return (
    <div className="footer-wrap">
      <footer class="footer">
        <div className="footer-logo-container">
          <StaticImage
            src="../images/external/logos/footer-logo.png"
            alt="MorPhiC logo"
            width={32.85}
            height={33}
            className="footer-logo"
          />
        </div>
        <div className="footer-content">
          <ul className="footer-menu">
            <li>
              <Link to="/">home</Link>
            </li>
            <li>
              <Link to="/about">About</Link>
            </li>
            <li>
              <Link to="/data">Data</Link>
            </li>
            <li>
              <a href="https://whri-phenogenomics.shinyapps.io/morphic_gene_list/" target="_blank" rel="noopener noreferrer">Gene list</a>
            </li>
            <li>
              <Link to="/#faq">FAQ</Link>
            </li>
            <li>
              <Link to="/contact">Contact us</Link>
            </li>
          </ul>
          <div className="footer-photo-credit">Photo by Sangharsh Lohakare on Unsplash</div>
          <div className="footer-copyright-container">
            <p className="footer-copyright-tile">Molecular Phenotypes of Null Alleles in Cells</p>
            <p className='footer-copyright'>&copy; 2024 MorPhiC. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
