// src/app/about/about.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit } from "@angular/core";
import { HeaderComponent } from "../header/header.component";
import { FooterComponent } from "../footer/footer.component";

@Component({
  selector: "my-component, MyComponent",
  imports: [HeaderComponent, FooterComponent],
  styleUrls: ['./about.component.scss'],
  templateUrl: './about.component.html',
  standalone: true,
  host: { class: 'about-page' }
})
export class AboutComponent {
  ngOnInit(): void {
    //Todo: Find a better way to override styles
    const elm = document.querySelector<HTMLElement>('.backdrop')!;
    elm.style.height = '15.5rem';
    const elm1 = document.querySelector<HTMLElement>('.orange-circle')!;
    elm1.style.left = '70.25%';
    const elm2 = document.querySelector<HTMLElement>('.white-circle')!;
    elm2.style.left = '70.35%';
  }
}
<app-header></app-header>
<div class="div sticky">
  <div class="white-triangle"></div>
  <div class="div-13">
    <div class="div-14">About</div>
    <div class="div-15 logo">
      <div class="div-16">
        <div class="column">
          <div class="div-17">
            A programme to better understand the function of every human
            gene and generate a catalogue of the molecular and cellular
            consequences of inactivating genes.
          </div>
        </div>
        <div class="column-2">
          <div class="div-18">
            <div class="div-19">inside this page</div>
            <div class="div-20">↓ The MorPhiC programme</div>
            <div class="div-21">↓ Publications</div>
            <div class="div-22">↓ What is null allele?</div>
            <div class="div-23">↓ Experiment design for the studies</div>
            <div class="div-24">↓ Data flow and availability</div>
            <div class="div-25">↓ Collaborators</div>
            <div class="div-26">↓ Funders</div>
          </div>
        </div>
      </div>
    </div>
    <div class="div-27">
      <div class="div-28">About the MorPhiC Program</div>
      <div class="div-29">↑ Back to top</div>
    </div>
    <div class="div-30">
      The MorPhiC programme aims to develop a consistent catalog of
      molecular and cellular phenotypes for null alleles for every human
      gene by using in-vitro multicellular systems. The catalog will be made
      available for broad use by the biomedical community. MorPhiC has three
      components: the Data Production Research and Development Centers
      (DPCs), the Data Analysis and Validation Centers (DAVs) and the Data
      Resource and Administrative Coordinating Center (DRACC).
    </div>
    <div class="div-31">
      <div class="div-32">Publications</div>
      <div class="div-33">↑ Back to top</div>
    </div>
    <div class="div-34">
      <div class="div-35">
        Description statement for the MorPhiC programme
      </div>
      <div class="div-36">Link to paper</div>
    </div>
    <div class="div-37">
      <div class="div-38">Data flow and availability</div>
      <div class="div-39">↑ Back to top</div>
    </div>
    <div class="data-flow-container">
      <section class="organisation">
        <h2>The MorPhic organisation</h2>
        <div class="categories">
          <div class="category">
            <h3>
              <span>Working Groups</span>
            </h3>
            <div class="items vectors-container">
              <div class="item item-bg-1 shadow">
                <img src="../../assets/external/logos/vector-e.png">
                <p class="label">EXPERIMENTAL</p>
              </div>
              <div class="item item-bg-2 shadow">
                <img src="../../assets/external/logos/vector-d.png">
                <p class="label">DATA</p>
              </div>
              <div class="item item-bg-3 shadow">
                <img src="../../assets/external/logos/vector-p.png">
                <p class="label">POLICY & OUTREACH</p>
              </div>
              <div class="item item-bg-1 item-4 shadow">
                <img src="../../assets/external/logos/vector-a.png">
                <p class="label">ANALYSIS</p>
              </div>
            </div>
          </div>
          <div class="category">
            <h3>
              <span>Data Production Centres</span>
            </h3>
            <div class="items white-box sticky" >
              <div class="logo-item">
                <img src="../../assets/external/logos/MSK.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Northwestern-no-border.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Jackson.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Stanford.png">
              </div>
              <div class="small-white-triangle sticky-triangle"></div>
            </div>
          </div>
          <div class="category">
            <h3>
              <span>Data Resource, Admin and Coordinating centres</span>
            </h3>
            <div class="items white-box sticky">
              <div class="logo-item zero-left">
                <img src="../../assets/external/logos/Miami.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Washington.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/EMBL.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Queen-Mary.png">
              </div>
              <div class="small-white-triangle sticky-triangle"></div>
            </div>
          </div>
          <div class="category">
            <h3>
              <span>Data Analysis and Validation Centres</span>
            </h3>
            <div class="items white-box last">
              <div class="logo-item">
                <img src="../../assets/external/logos/Stanford.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Fred-Hutch.png">
              </div>
              <div class="logo-item">
                <img src="../../assets/external/logos/Jackson.png">
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <div class="div-40">
      The MorPhiC programme aims to develop a consistent catalog of
      molecular and cellular phenotypes for null alleles for every human
      gene by using in-vitro multicellular systems. The catalog will be made
      available for broad use by the biomedical community. MorPhiC has three
      components: the Data Production Research and Development Centers
      (DPCs), the Data Analysis and Validation Centers (DAVs) and the Data
      Resource and Administrative Coordinating Center (DRACC).
    </div>
    <div class="div-41">
      <div class="div-42">Funders</div>
      <div class="div-43">↑ Back to top</div>
    </div>
    <div class="div-44">
      <div class="div-45">
        <div class="div-46">NIH Grant #1234567890</div>
        <div class="div-47">NIH Grant #1234567890</div>
        <div class="div-48">NIH Grant #1234567890</div>
        <div class="div-49">NIH Grant #1234567890</div>
      </div>
      <div class="div-50">
        <div class="div-51">Link to paper</div>
        <div class="div-52">Link to paper</div>
        <div class="div-53">Link to paper</div>
        <div class="div-54">Link to paper</div>
      </div>
    </div>
  </div>
</div>
<app-footer></app-footer>

// react-app/src/pages/about.js
import React from "react"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import { StaticImage } from "gatsby-plugin-image"

export default function About() {
  return (
    <div className="about">
      <div>
        <Navbar />
        <div className="policies-triangle"></div>
      </div>
      
      <div className="about-container">
        <div className="about-info-container">
          <div className="about-info">
            <div>
              <h1>About</h1>
              <div className="about-intro-container">
                <div className="about-intro">
                  <p>A program to better understand the function of every human gene and generate a catalogue of the molecular and cellular consequences of inactivating genes.</p>
                  <div className="about-card-container">
                    <div className="about-card">
                      <h2 className="about-card-title">inside this page</h2>
                      <ul>
                        <li><a href="#program-goals">↓ Program goals</a></li>
                        <li><a href="#participants">↓ Participants</a></li>
                        <li><a href="#funding">↓ Funding</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <section id="program-goals" className="about-section">
              <div className="about-section-subtitle-container">
                <h2>Program goals</h2>
                <a href="#">↑ Back to top</a>
              </div>
              <div className="about-section-description-container">
                <p>
                  MorPhiC aims to develop a consistent catalog of molecular and cellular phenotypes for null alleles for every human gene by using in-vitro multicellular systems. The catalog will be made available for broad use by the biomedical community. The program will start with a Phase 1 to optimize available methods to create null alleles and measure their phenotypic effects in a target subset of 1,000 protein coding genes across the program. Phase 1 will also assess the scale limitations of such methods, develop common data formats and establish use cases for this catalog.
                </p>
                <p>
                  Systematically obtaining information about the molecular and cellular phenotypic effects of gene knockouts for all human genes would provide wide-ranging insights into their biological function. Such data would provide a foothold for understanding the mechanisms through which genes act to produce phenotypes and would help elucidate the roles and relationships of genes and regulatory elements in pathways and networks.
                </p>
                <p><b>MorPhiC Phase 1</b> will include three components:</p>
                <p>
                  <b>Data Production Research and Development Centers</b> will develop diverse systems and assays and explore and compare approaches to produce MorPhiC data at scale, and to maximize its informativeness.
                </p>
                <p>
                  <b>Data Analysis and Validation Centers</b> will undertake applicant-proposed analyses of the data in order to characterize its quality and utility for multiple purposes.
                </p>
                <p>
                  There will be a <b>Data Resource and Administrative Coordinating Center.</b>
                </p>
                <p>All components will work together to ensure that the data are informative, of high quality and useful to the community.</p>
              </div>
            </section>

            <section id="participants" className="about-section">
              <div className="about-section-subtitle-container">
                <h2>Participants</h2>
                <a href="#">↑ Back to top</a>
              </div>
            </section>

            <div className="data-flow-card">
              <section className="organisation">
                <h2>The MorPhiC participants</h2>
                <div className="data-flow-categories">
                  <div className="data-flow-category">
                    <h3 className="data-flow-sub-heading"><span>Working Groups</span></h3>
                    <div className="data-flow-items">
                      <div className="data-flow-item item-bg-1">
                        <span aria-hidden className="data-flow-item-icon icon-group"></span>
                        <p className="item-label">Experimental</p>
                      </div>
                      <div className="data-flow-item item-bg-2">
                        <span aria-hidden className="data-flow-item-icon icon-category"></span>
                        <p className="item-label">data</p>
                      </div>
                      <div className="data-flow-item item-bg-3">
                        <span aria-hidden className="data-flow-item-icon icon-list"></span>
                        <p className="item-label">policy & outreach</p>
                      </div>
                      <div className="data-flow-item item-bg-4">
                        <span aria-hidden className="data-flow-item-icon icon-gear"></span>
                        <p className="item-label">analysis</p>
                      </div>
                    </div>
                  </div>
                  <div className="data-flow-category">
                    <h3><span>data production centres</span></h3>
                    <div className="data-flow-items white-box flex-space-evenly">
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/MSK.png"
                          alt="Sloan-Kettering Institute for Cancer Research"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Northwestern-no-border.png"
                          alt="Northwestern University Feinberg School of Medicine"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Jackson.png"
                          alt="Jackson Laboratory"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/UCSF.png"
                          alt="Stanford of California San Francisco"
                          className="data-flow-logo"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="data-flow-category">
                    <h3><span>data resource, admin and coordinating centrE</span></h3>
                    <div className="data-flow-items white-box flex-space-evenly">
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Miami.png"
                          alt="University of Miami"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Washington.png"
                          alt="University of Washington"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/EMBL.png"
                          alt="EMBL"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Queen-Mary.png"
                          alt="Queen Mary University of London"
                          className="data-flow-logo"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="data-flow-category">
                    <h3><span>data analysis and validation centres</span></h3>
                    <div className="data-flow-items white-box flex-space-evenly">
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Stanford.png"
                          alt="Stanford University"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Fred-Hutch.png"
                          alt="Fred Hutchinson Cancer Center"
                          className="data-flow-logo"
                        />
                      </div>
                      <div className="data-flow-logo-item">
                        <StaticImage
                          src="../images/external/logos/Jackson.png"
                          alt="Jackson Laboratory"
                          className="data-flow-logo"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>

            <section id="funding" className="about-section">
              <div className="about-section-subtitle-container">
                <h2>Funding</h2>
                <a href="#">↑ Back to top</a>
              </div>
              <div className="about-section-description-container">
                <p>
                  Read the <a className="" href="https://www.genome.gov/research-funding/Funded-Programs-Projects/Molecular-Phenotypes-of-Null-Alleles-in-Cells" target="_blank" rel="noopener noreferrer">
                  MorPhiC Program outline on the NHGRI website →</a>
                </p>
              </div>
            </section>

            <Footer />
          </div>
        </div>
      </div>
    </div>
  )
}

export function Head() {
  return (
    <>
      <title>MorPhiC program: Molecular Phenotypes of Null Alleles in Cells</title>
      <link id="icon" rel="icon" href="favicon.svg" />
    </>
  )
}
